version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: food_recipes_db
    environment:
      POSTGRES_USER: food_user
      POSTGRES_PASSWORD: food_password
      POSTGRES_DB: food_recipes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - food_network

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food_recipes_backend
    environment:
      DATABASE_URL: postgresql://food_user:food_password@db:5432/food_recipes
      SECRET_KEY: your-super-secret-key-change-in-production
      HOST: 0.0.0.0
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - food_network
    restart: unless-stopped

  # Adminer for database management (optional)
  adminer:
    image: adminer
    container_name: food_recipes_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - food_network

volumes:
  postgres_data:

networks:
  food_network:
    driver: bridge